/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Full Stack FastAPI Project
 * OpenAPI spec version: 0.1.0
 */
import type { ItemPublic } from './itemPublic';

export interface ItemsPublic {
  data: ItemPublic[];
  count: number;
}
