/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Full Stack FastAPI Project
 * OpenAPI spec version: 0.1.0
 */
import type { ItemUpdateTitle } from './itemUpdateTitle';
import type { ItemUpdateDescription } from './itemUpdateDescription';

export interface ItemUpdate {
  title?: ItemUpdateTitle;
  description?: ItemUpdateDescription;
}
