/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Full Stack FastAPI Project
 * OpenAPI spec version: 0.1.0
 */
import type { ItemPublicDescription } from './itemPublicDescription';

export interface ItemPublic {
  /**
   * @minLength 1
   * @maxLength 255
   */
  title: string;
  description?: ItemPublicDescription;
  id: string;
  owner_id: string;
}
