/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Full Stack FastAPI Project
 * OpenAPI spec version: 0.1.0
 */
import type { UserPublicFullName } from './userPublicFullName';

export interface UserPublic {
  /** @maxLength 255 */
  email: string;
  is_active?: boolean;
  is_superuser?: boolean;
  full_name?: UserPublicFullName;
  id: string;
}
