/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Full Stack FastAPI Project
 * OpenAPI spec version: 0.1.0
 */
import type { UserUpdateEmail } from './userUpdateEmail';
import type { UserUpdateFullName } from './userUpdateFullName';
import type { UserUpdatePassword } from './userUpdatePassword';

export interface UserUpdate {
  email?: UserUpdateEmail;
  is_active?: boolean;
  is_superuser?: boolean;
  full_name?: UserUpdateFullName;
  password?: UserUpdatePassword;
}
