/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Full Stack FastAPI Project
 * OpenAPI spec version: 0.1.0
 */
import type { UserUpdateMeFullName } from './userUpdateMeFullName';
import type { UserUpdateMeEmail } from './userUpdateMeEmail';

export interface UserUpdateMe {
  full_name?: UserUpdateMeFullName;
  email?: UserUpdateMeEmail;
}
