/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Full Stack FastAPI Project
 * OpenAPI spec version: 0.1.0
 */
import type { UserPublic } from './userPublic';

export interface UsersPublic {
  data: UserPublic[];
  count: number;
}
