/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Full Stack FastAPI Project
 * OpenAPI spec version: 0.1.0
 */
import type { UserRegisterFullName } from './userRegisterFullName';

export interface UserRegister {
  /** @maxLength 255 */
  email: string;
  /**
   * @minLength 8
   * @maxLength 40
   */
  password: string;
  full_name?: UserRegisterFullName;
}
