/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Full Stack FastAPI Project
 * OpenAPI spec version: 0.1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';

import type {
  UserPublic
} from '.././models';


export const getPrivateCreateUserResponseMock = (overrideResponse: Partial< UserPublic > = {}): UserPublic => ({email: faker.internet.email(), is_active: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), is_superuser: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), full_name: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 255}}),null,]), undefined]), id: faker.string.uuid(), ...overrideResponse})


export const getPrivateCreateUserMockHandler = (overrideResponse?: UserPublic | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<UserPublic> | UserPublic)) => {
  return http.post('*/api/v1/private/users/', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPrivateCreateUserResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}
export const getPrivateMock = () => [
  getPrivateCreateUserMockHandler()
]
